//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da Resource.rc
//
#define IDR_COLLISION_STONE1			100
#define IDR_COLLISION_STONE2			101
#define IDR_COLLISION_STONE3			102
#define IDR_COLLISION_MARBLE1			103
#define IDR_COLLISION_MARBLE2			104
#define IDR_COLLISION_MARBLE3			105
#define IDR_COLLISION_GRAVEL1			106
#define IDR_COLLISION_GRAVEL2			107
#define IDR_COLLISION_GRAVEL3			108
#define IDR_COLLISION_SAND1				109
#define IDR_COLLISION_SAND2				110
#define IDR_COLLISION_SAND3				111
#define IDR_COLLISION_MUD1				112
#define IDR_COLLISION_MUD2				113
#define IDR_COLLISION_MUD3				114
#define IDR_COLLISION_GRASS1			115
#define IDR_COLLISION_GRASS2			116
#define IDR_COLLISION_GRASS3			117
#define IDR_COLLISION_TALL_GRASS1		118
#define IDR_COLLISION_TALL_GRASS2		119
#define IDR_COLLISION_TALL_GRASS3		120
#define IDR_COLLISION_CARPET1			121
#define IDR_COLLISION_CARPET2			122
#define IDR_COLLISION_CARPET3			123
#define IDR_COLLISION_WOOD1				124
#define IDR_COLLISION_WOOD2				125
#define IDR_COLLISION_WOOD3				126
#define IDR_COLLISION_CREAKY_WOOD1		127
#define IDR_COLLISION_CREAKY_WOOD2		128
#define IDR_COLLISION_CREAKY_WOOD3		129
#define IDR_COLLISION_METAL1			130
#define IDR_COLLISION_METAL2			131
#define IDR_COLLISION_METAL3			132
#define IDR_COLLISION_CREAKY_METAL1		133
#define IDR_COLLISION_CREAKY_METAL2		134
#define IDR_COLLISION_CREAKY_METAL3		135
#define IDR_COLLISION_ROCK1				136
#define IDR_COLLISION_ROCK2				137
#define IDR_COLLISION_ROCK3				138
#define IDR_COLLISION_UNSAFE_ROCK1		139
#define IDR_COLLISION_UNSAFE_ROCK2		140
#define IDR_COLLISION_UNSAFE_ROCK3		141
#define IDR_COLLISION_WATER_PUDDLE1		142
#define IDR_COLLISION_WATER_PUDDLE2		143
#define IDR_COLLISION_WATER_PUDDLE3		144
#define IDR_COLLISION_WET_WOOD			145
#define IDR_COLLISION_WET_METAL			146
#define IDR_COLLISION_WET_STONE			147
#define IDR_COLLISION_SNOW1				148
#define IDR_COLLISION_SNOW2				149
#define IDR_COLLiSION_SNOW3				150
#define IDR_COLLISION_RUBBER			151
#define IDR_COLLISION_SKIP				152
#define IDR_COLLISION_GLASS_PANEL		153
#define IDR_COLLISION_ICE				154
#define IDR_COLLISION_WET_GRAVEL		155
#define IDR_COLLISION_WET_CARPET		156
#define IDR_COLLISION_WET_GRASS			157
#define IDR_COLLISION_WET_SAND			158
#define IDR_COLLISION_WET_RUBBER		159
#define IDR_COLLISION_WET_SKIP			160

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
